// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rvucrivhtgrjrymrtnwy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ2dWNyaXZodGdyanJ5bXJ0bnd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0ODI0NTAsImV4cCI6MjA2MDA1ODQ1MH0.fGTQfbY4lxaeMzHK1qk-Og9abJ0kBo89h1D1dJ9WTE4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);